name: Quality Checks

on:
  pull_request:

jobs:
  quality:
    permissions:
      contents: read
    uses: aimsmaulikk/ci-workflows/.github/workflows/quality-gate.yml@main
    with:
      php-version: "8.3"
      enable-phpstan: true
      enable-ai-review: true
      enable-magento-compile: true
      enable-pr-comments: true
      ci-workflows-repository: "aimsmaulikk/ci-workflows"
      ci-workflows-ref: "main"