name: Quality Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Validate composer.json
        run: composer validate

      - name: Install PHPCS
        run: |
          mkdir tools
          cd tools
          composer require squizlabs/php_codesniffer --no-interaction

      - name: Run PHPCS
        run: tools/vendor/bin/phpcs --standard=phpcs.xml .